# Workflow name
name: Publish Docker Image to GitHub Container Registry

# Controls when the action will run. 
# Triggers the workflow on push events but only for the main branch.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds the Docker image and pushes it to GitHub Container Registry
  build_and_push_docker_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Permissions needed by the job.
    # `contents: read` is to checkout the repository.
    # `packages: write` is to push the Docker image to GitHub Container Registry.
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out the repository code
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry (ghcr.io)
      # This action logs in the Docker client to a container registry.
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # ${{ github.actor }} is the username of the user that triggered the workflow.
          # For pushes to the repository, this is usually the repository owner.
          username: ${{ github.actor }}
          # ${{ secrets.GITHUB_TOKEN }} is a special token provided by GitHub Actions
          # that has permissions to push to the repository's package registry.
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and push Docker image to GitHub Container Registry
      # This action builds a Docker image and pushes it to a registry.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # context: Path to the directory containing the Dockerfile and build context.
          # '.' means the root of the repository.
          context: .
          # push: Whether to push the image after building. 'true' means push.
          push: true
          # tags: A list of tags for the image.
          # We are tagging with the Git SHA for versioning and 'latest' for the most recent version.
          # ${{ github.repository_owner }} is the owner of the repository (e.g., your GitHub username or organization name).
          # 'discord-role-bot' is the placeholder for the image name.
          # ${{ github.sha }} is the commit SHA that triggered the workflow.
          tags: |
            ghcr.io/${{ github.repository_owner }}/discord-role-bot:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/discord-role-bot:latest
